apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  name: snapshotcontent-manual
spec:
  deletionPolicy: Retain
  driver: dobs.csi.digitalocean.com
  source:
    snapshotHandle: 92b46522-4798-4544-9d33-8b74ea56adb7
  volumeSnapshotRef:
    name: snapshot-manual
    namespace: default
